name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - run: make setup
    - name: Lint
      run: make lint
    - name: test
      run: make test
