name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - name: Setup Dependencies
      run: make setup-ci
    - name: Lint
      run: make lint-ci
    - name: Test
      env:
        ALGOLIA_APPLICATION: ${{ secrets.ALGOLIA_APPLICATION }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_INDEX: ${{ secrets.ALGOLIA_INDEX }}
      run: make test
